#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $APP_USER WITH PASSWORD '$APP_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $APP_USER;

    CREATE USER flyway_user WITH PASSWORD 'strong_password';
    GRANT CONNECT ON DATABASE "$POSTGRES_DB" TO flyway_user;

    GRANT USAGE, CREATE ON SCHEMA public TO flyway_user;

    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO flyway_user;

    GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO flyway_user;

    ALTER DEFAULT PRIVILEGES FOR ROLE $APP_USER IN SCHEMA public
       GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO flyway_user;

    ALTER DEFAULT PRIVILEGES FOR ROLE $APP_USER IN SCHEMA public
       GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO flyway_user;
EOSQL
