CREATE TABLE permissions
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    permission_name VARCHAR(255)                            NOT NULL,
    version         INTEGER,
    CONSTRAINT pk_permissions PRIMARY KEY (id)
);

ALTER TABLE permissions
    ADD CONSTRAINT uc_permissions_permissionname UNIQUE (permission_name);

CREATE INDEX idx_permission_name ON permissions (permission_name);